baseURL = "https://imaginative-axolotl-5bd7be.netlify.app/"
languageCode = "en-gb"
title = "Universal Safety Consultants"

# We are NOT using a Hugo theme folder
theme = ""

[params]
  description = "Training, audit and safety consultancy services"

[outputs]
  home = ["HTML"]
